### ISSUE TITLE
`install-cmdstan`: Windows is failing to install cmdstan

### ISSUE THREAD

**Issue by seabbs** [epinowcast/actions#1]
As above in the current version of the action windows is failing to install cmdstan. However this looks like a wider issue with `cmdstanr` rather than with the action so in the first instance I suggest monitoring to see if this is fixed upstream (and contributing there if you have any thoughts). 

See: https://github.com/epinowcast/epinowcast/actions/runs/7779464747/job/21210655196

**Comment by sbfnk** [comment]
Mentioned in https://github.com/stan-dev/cmdstanr/issues/916

**Comment by seabbs** [comment]
This seems fixed now.
