### ISSUE TITLE
Problem with caching

### ISSUE THREAD

**Issue by sbfnk** [epinowcast/actions#24]
GHA on this PR in EpiNow2 failed until I deleted the cache:
https://github.com/epiforecasts/EpiNow2/pull/769

**Comment by seabbs** [comment]
Potentially this is due to a mismatch between cmdstanr and cmdstan? We could make the cache take version numbers for each but I can't see that this is likely the case. 

I think my vote is close this for now and reopen with more detail if this turns out to note be transcient.

**Comment by sbfnk** [comment]
Sounds good - it was quite tricky for me to identify this as the problem (no obvious error message etc) so will need to keep this int he back of our minds for any cmdstanr issues that might pop up in GHA.

**Comment by seabbs** [comment]
I think if there is somewhere can put something like: Caching is often randomly a problem. If you have a problem somewhere that there is caching step 1. to debug is remove cache and rerun
